// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Apply a patch to an existing thread's workspace through the native
 * file-change approval chain.
 */
export type CodexApplyPatchParams = {
/**
 * Thread the patch is associated with. The thread must exist; the
 * file-change approval request references this thread.
 */
threadId: string,
/**
 * Patch payload in the Codex `apply_patch` grammar
 * (`*** Begin Patch` ... `*** End Patch`).
 */
patch: string,
/**
 * Working directory used to resolve relative patch paths. Defaults to the
 * thread's configured cwd.
 */
cwd?: string | null,
/**
 * Optional explanatory reason surfaced in the approval request.
 */
reason?: string | null, };
