// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `codex/spawnAgent`.
 */
export type CodexSpawnAgentResponse = {
/**
 * Id of the forked child thread.
 */
childThreadId: string, };
