// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Read a thread's history in either structured or projected plain-text form.
 */
export type CodexGetHistoryParams = {
/**
 * Thread to read.
 */
threadId: string,
/**
 * `"full"` returns structured turns; `"compact"` returns a plain-text
 * projection of the same projected history. Defaults to `"compact"`.
 */
mode?: string | null, };
