// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fork a child thread from an existing parent thread and start its first
 * turn with the supplied prompt.
 */
export type CodexSpawnAgentParams = {
/**
 * Parent thread to fork from.
 */
parentThreadId: string,
/**
 * Initial task given to the child thread.
 */
prompt: string,
/**
 * Optional role recorded in the child thread's metadata.
 */
agentRole?: string | null,
/**
 * Optional model override for the child thread.
 */
model?: string | null, };
