// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Turn } from "./Turn";

/**
 * Result of `codex/getHistory`, tagged by the requested mode.
 */
export type CodexGetHistoryResponse = { "mode": "full", turns: Array<Turn>, } | { "mode": "compact", text: string, };
