// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `codex/applyPatch`.
 */
export type CodexApplyPatchResponse = {
/**
 * Whether the patch was approved and written to disk. `false` when the
 * file-change approval request was declined or cancelled.
 */
applied: boolean,
/**
 * Native paths of the files touched by the patch.
 */
fileChanges: Array<string>, };
